config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/items')

  get 'items/tag'
  resources :items do
    collection { post :import }
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  acts_as_ordered_taggable_on :tags
    acts_as_taggable

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      item = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      item.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
      item.save!
    end
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["name", "bunrui", "bangou"]
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  before_filter :tag_cloud, :tag

  def tag_cloud
      @tags = Item.tag_counts_on(:tags).order('counts DESC')
  end

  def tag
    @items = Item.tagged_with(params[:tag_name])
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def import
    # fileはtmpに自動で一時保存される
    Item.import(params[:file])
    redirect_to root_url, notice: "add items"
  end


  def tag_cloud
      @tags = Item.tag_counts_on(:tags)
  end

  def item_params
    params.require(:item).permit(:name, :tag_list, :hurigana, :date, :bunrui, :bangou, :gozyuon, :picture)
  end

  def tag
    @items = Item.tagged_with(params[:tag_name])


  end
  # GET /items
  # GET /items.json
  def index

    @q = Item.search(params[:q])
    @items = @q.result.order("updated_at DESC").page(params[:page]).per(10)
    @tags = Item.tag_counts_on(:tags)

    #items = Item.all
    # @q = Item.search(params[:q])
    # @items = @q.result(distinct: true)
    # @items = Item.page(params[:page]).per(15)
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def item_params
      # params.require(:item).permit(:name, :hurigana, :date, :bunrui, :bangou, :gozyuon, :tag_list)
    # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :hurigana %><br>
    <%= f.text_field :hurigana %>
    <script type="text/javascript">
      $(document).ready(
          function() {
              $.fn.autoKana('#item_name', '#item_hurigana', {
                  katakana : true  //true：カタカナ、false：ひらがな（デフォルト）
          });
      });
    </script>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :bunrui %><br>
    <%= f.text_field :bunrui %>
  </div>
  <div class="field">
    <%= f.label :bangou %><br>
    <%= f.text_field :bangou %>

  </div>
  <div class="field">
    <%= f.label :gozyuon %><br>
    <%= f.text_field :gozyuon %>
  </div>
  <div class="field">
    <%= f.label :tag_list %><br>
    <%= text_field_tag 'item[tag_list]', @item.tag_list.join(','), "data-role" => "tagsinput" %>
  </div>
  <div class "field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/_tag_list.html.erb
<% tag_list.each do |tag| %>
  <!-- bootstrap付きタグ -->
  <!-- <span class="label label-primary"><%= link_to tag,{ action: :tag, :tag_name => tag } %></span> -->
  <span><%= link_to tag,{ action: :tag, :tag_name => tag } %></span>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Listing Items</h1>
<%= search_form_for @q do |f| %>

  <div>
    <%= f.label :name_or_hurigana_cont, "Title" %>
    <%= f.text_field :name_or_hurigana_cont %>
  </div>

  <div>
    <%= f.label :bunrui_cont, "Bunrui" %>
    <%= f.text_field :bunrui_cont %>
  </div>

  <div>
    <%= f.label :bangou_cont, "Banngou" %>
    <%= f.text_field :bangou_cont %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

<br>
<%= form_tag import_items_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>
<br>



<%= page_entries_info @items %>
<div class="container, clearfix">
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= sort_link(@q, :name) %></th>
        <th>Bunrui</th>
        <th>Bangou</th>
        <th>Tag</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= link_to item.name, item %></td>
          <td><%= item.bunrui %></td>
          <td><%= item.bangou %></td>
          <td><%= render "items/tag_list", tag_list: item.tag_list %></td>
          <td><%= link_to edit_item_path(item) do %>
            <span class="fa fa-pencil" aria-hidden="true"></span><% end %>
          </td>
          <td><%= link_to item, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="fa fa-trash-o"></span><% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= paginate @items %>

<br />
<%= link_to 'Back', items_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container, clearfix">
  <table class="table table-striped">
    <tr>
      <td class="col-sm-2"><strong>Name</strong></td>
      <td class="col-sm-6"><%= @item.name %></td>
    </tr>

    <tr>
      <td><strong>Hurigana</strong>
      <td><%= @item.hurigana %></td>
    </tr>

    <tr>
      <td><strong>Date</strong></td>
      <td><%= @item.date %></td>
    </tr>

    <tr>
      <td><strong>Bunrui</strong></td>
      <td><%= @item.bunrui %></td>
    </tr>

    <tr>
      <td><strong>Bangou</strong></td>
      <td><%= @item.bangou %></td>
    </tr>

    <tr>
      <td><strong>Gozyuon</strong></td>
      <td><%= @item.gozyuon %></td>
    </tr>

    <tr>
      <td><strong>Tag</strong></td>
      <td><%= render "items/tag_list", tag_list: @item.tag_list %></td>
    </tr>

  </table>
</div>





<%= image_tag(@item.picture_url, width: 200) if @item.picture.present? %>

</br>
</br>
<%= link_to edit_item_path(@item) do %><span class="fa fa-pencil"></span><% end %> |
<%= link_to 'Back', items_path %>

</br>

app/views/items/tag.html.erb
<!--
      <% @items.each do |item| %>
       <%= item.name %>
       <%= item.bunrui %></td>
       <%= item.bangou %></td>
       <% item.tags.each do |tag| %>
        <%= tag.name %>
       <% end %>
       <br />
      <% end %> -->



  <div class="container, clearfix">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Bunrui</th>
          <th>Bangou</th>
          <th>Tag</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @items.each do |item| %>
          <tr>
            <td><%= link_to item.name, item %></td>
            <td><%= item.bunrui %></td>
            <td><%= item.bangou %></td>
            <td><%= render "items/tag_list", tag_list: item.tag_list %></td>
            <td><%= link_to edit_item_path(item) do %>
              <span class="fa fa-pencil" aria-hidden="true"></span><% end %>
            </td>
            <td><%= link_to item, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="fa fa-asterisk"></span><% end %>
            </td>
        <% end %>
      </tbody>
    </table>
  </div>

  <%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Soturon2" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <!--<%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>-->

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <!--<%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>-->

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <!--<%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>-->

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <!--<%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>-->

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <!--<%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>-->

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/items">Soturon2</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "New item", new_item_path  %></li>
            <!-- <li><%= link_to "Link2", "/path2"  %></li> -->
            <!-- <li><%= link_to "Link3", "/path3"  %></li> -->
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
              <%= link_to tag.name, { action: :tag, :tag_name => tag.name }, :class => css_class %>
            <% end %>
            <!-- <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul> -->
          </div> <!--/.well-->
        </div> <!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>